"""create songs table

Revision ID: 46c33f2ec7ab
Revises: def47d70f370
Create Date: 2021-01-05 15:17:20.096065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46c33f2ec7ab'
down_revision = 'def47d70f370'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artistId', sa.Integer(), nullable=True),
    sa.Column('songName', sa.String(), nullable=False),
    sa.Column('albumName', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['artistId'], ['artists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('songs')
    # ### end Alembic commands ###
